# Use a lightweight Python image
FROM python:3.13.1

# Set the working directory
WORKDIR /app
ENV PYTHONPATH=/app
# Copy everything (folder in which this file lives) inside the recommender_system directory
COPY cs_module /app/cs_module

RUN pip install -r /app/cs_module/requirements.txt

# Run the main script
CMD ["python", "-u", "-m", "cs_module.cs_api"]





